### ISSUE TITLE
Catapult don't compile in Slackware 10.2

### ISSUE THREAD

**Issue by andete** [openMSX/openMSX#226]
**Reported by witchopaan on 2006-01-30 17:51 UTC**

Hi pals

When i try to compile catapult 0.6.0 \(R1 or R2\) in my
fresh Slackware 10.2 \(gcc 3.3.6\), got \*\*\*

That is a GCC or a Catapult problem?
\(maybe using 3.4\)

Thanks in advance
Wilson Pilon

\*\*\*
witcho@msx:~/tmp/openmsx-catapult-0.6.0-R1$ make
Autodetecting native system:
Using config.guess of 2004-03-03...
Detected system: i686-pc-linux-gnu
Probing target system...

Found libraries:
wxWidgets:       2.6.2
wxWidgets XRC:   yes
libxml2:         2.6.22

Found headers:
wxWidgets:       yes
wxWidgets XRC:   yes
libxml2:         yes

Customizable options:
Install to:                       /opt/openMSX-Catapult
Default openMSX binary location: 
/opt/openMSX/bin/openmsx
Default openMSX system share dir: /opt/openMSX/share
\(you can edit these in build/custom.mk\)

Creating derived/x86-linux-i686/config/config.h...
Creating derived/x86-linux-i686/config/Version.ii...
Build configuration
Platform: x86-linux
Flavour:  i686
Compiling openMSXLinuxController...
Compiling CatapultPage...
Compiling wxCatapultApp...
Compiling wxCatapultFrm...
src/wxCatapultFrm.cpp: In constructor \`
wxCatapultFrame::wxCatapultFrame\(wxWindow\*\)':
src/wxCatapultFrm.cpp:215: error: syntax error before
\`;' token
src/wxCatapultFrm.cpp:216: error: syntax error before
\`;' token
make: \*\*\* \[derived/x86-linux-i686/obj/wxCatapultFrm.o\]
Error 1
