### ISSUE TITLE
[Bug] Catapult don't compile in Slackware 10.2 [sf#226]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#527]
**Reported by witchopaan on 2006-01-30 17:51 UTC**

Hi pals

When i try to compile catapult 0.6.0 (R1 or R2) in my
fresh Slackware 10.2 (gcc 3.3.6), got ***

That is a GCC or a Catapult problem?
(maybe using 3.4)

Thanks in advance
Wilson Pilon

***
witcho@msx:~/tmp/openmsx-catapult-0.6.0-R1$ make
Autodetecting native system:
Using config.guess of 2004-03-03...
Detected system: i686-pc-linux-gnu
Probing target system...

Found libraries:
wxWidgets:       2.6.2
wxWidgets XRC:   yes
libxml2:         2.6.22

Found headers:
wxWidgets:       yes
wxWidgets XRC:   yes
libxml2:         yes

Customizable options:
Install to:                       /opt/openMSX-Catapult
Default openMSX binary location: 
/opt/openMSX/bin/openmsx
Default openMSX system share dir: /opt/openMSX/share
(you can edit these in build/custom.mk)

Creating derived/x86-linux-i686/config/config.h...
Creating derived/x86-linux-i686/config/Version.ii...
Build configuration
Platform: x86-linux
Flavour:  i686
Compiling openMSXLinuxController...
Compiling CatapultPage...
Compiling wxCatapultApp...
Compiling wxCatapultFrm...
src/wxCatapultFrm.cpp: In constructor `
wxCatapultFrame::wxCatapultFrame(wxWindow*)':
src/wxCatapultFrm.cpp:215: error: syntax error before
`;' token
src/wxCatapultFrm.cpp:216: error: syntax error before
`;' token
make: *** [derived/x86-linux-i686/obj/wxCatapultFrm.o]
Error 1

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2006-01-30 18:08 UTC**
Logged In: YES 
user_id=78178

Hi,

Indeed, it doesn't compile on gcc 3.3, it does compile on
gcc 3.4 and higher though :(

It seems I put an extra pair of parentheses around the throw
object, which doesn't compile on 3.3 :((((

If you want to work around it, use this patch:

diff -u -r1.86 wxCatapultFrm.cpp
--- src/wxCatapultFrm.cpp       27 Jan 2006 19:07:53 -0000 
1.86
+++ src/wxCatapultFrm.cpp       30 Jan 2006 18:08:02 -0000
@@ -213,8 +213,8 @@
this-&gt;GetSizer()-&gt;SetSizeHints(this);
m_sessionPage-&gt;RestoreHistory();
m_sessionPage-&gt;SetupHardware(false,
viewMenu-&gt;IsChecked(Catapult_Display_Invalids));
-               } else throw(NoOpenMSXBinaryException());
-       } else throw(NoOpenMSXBinaryException());
+               } else throw NoOpenMSXBinaryException();
+       } else throw NoOpenMSXBinaryException();
}

// frame destructor

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2006-01-30 18:18 UTC**
Logged In: YES 
user_id=78178

Fixed in CVS now as well, but I'm not sure we'll do another
re-release for this.... You should have told me this one day
sooner!

**Comment by openMSX-import** [comment]
**Updated by manuelbi on 2006-01-30 18:18 UTC**
- **assigned_to**: nobody --> manuelbi
- **status**: open --> closed-fixed
