### ISSUE TITLE
MacOS build broken by commit 2663770 by @m9710797

### ISSUE THREAD

**Issue by sdsnatcher73** [openMSX/openMSX#1322]
@m9710797 committed [https://github.com/openMSX/openMSX/commit/26637700cb31ecb5b2c06fa7fd8eb745ca58c6e6](Change return type from 'const string&' to 'string_view' This patch changes the return type for (some) virtual methods that return 'const std::string&' to 'std::string_view'...) This commit broke the macOS build on clang:

In file included from src/PluggableFactory.cc:31:
src/serial/MidiOutCoreMIDI.hh:72:35: error: virtual function 'getName' has a different return type ('const std::string &' (aka 'const basic_string<char, char_traits<char>, allocator<char> > &')) than the function it overrides (which has return type 'std::string_view' (aka 'basic_string_view<char>'))
        [[nodiscard]] const std::string& getName() const override;
                            ~~~~~~~~~~~~ ^
src/Pluggable.hh:18:41: note: overridden virtual function is here
        [[nodiscard]] virtual std::string_view getName() const;
                              ~~~~~~~~~~~~~~~~ ^
1 error generated.
make[1]: *** [derived/x86_64-darwin-opt-3rd/obj/PluggableFactory.cc.o] Error 1
make: *** [staticbindist] Error 2

Not sure if this is because clang is more strict than gcc or something else.

**Comment by sdsnatcher73** [comment]
probably this code is not built on Linux and Windows as It targets CoreMidi...

**Comment by sdsnatcher73** [comment]
Seems one [[nodiscard]] const std::string& getName() was left in MidiOutCoreMidi.hh, I changed it and build proceeds not. Will create a pull request if it fixes the whole build.

**Comment by m9710797** [comment]
Ok, thanks.
I indeed can't test MacOS specific code. I do my best to not break it, but sometimes I miss stuff :(

**Comment by sdsnatcher73** [comment]
Tested the build with FS-A1GT machine and midi out routed through Munt CM32L emulator and it works fine (on a macOS of course)
