### ISSUE TITLE
Notice of imgui's Shortcut API changes

### ISSUE THREAD

**Issue by ocornut** [openMSX/openMSX#1630]
Notice for when you update, as I reckon you were early users because I mentioned the API:
Please note that I have just started making `ImGui::Shortcut()` and associated things this public API, and before doing so I have pushed various breaking changes.
- https://github.com/ocornut/imgui/commit/b4f564c1ed7db124c0ef45368dc2916bb5964e56 Renamed `ImGuiInputFlags_RouteGlobalLow` -> `ImGuiInputFlags_RouteGlobal`, `ImGuiInputFlags_RouteGlobal` -> `ImGuiInputFlags_RouteGlobalOverFocused`, `ImGuiInputFlags_RouteGlobalHigh` -> `ImGuiInputFlags_RouteGlobalHighest`
- https://github.com/ocornut/imgui/commit/55748cdbe12369c1b90b90cc3676ae0699c2611d Renamed `ImGuiKeyOwner_None` to `ImGuiKeyOwner_NoOwner`.
- https://github.com/ocornut/imgui/commit/900b29055c5da1546b7d68ad52e0e4e61facb701 Swapped two last default parameters of Shortcut().
- https://github.com/ocornut/imgui/commit/85513de247614cfd72c59bbfcb53c82823f08068 Swapped two last default parameters for owner-aware versions of IsKeyPressed(), IsKeyChordPressed(), IsMouseClicked().

**Comment by m9710797** [comment]
Thanks for the heads-up!

**Comment by ocornut** [comment]
The last two are unusually harsh breakage (I don't think I ever done that before in public API), but I think they are for the best and ultimately will be long forgotten soon.

**Comment by ocornut** [comment]
Clarification on the above, since 1.90.7 is now released and this is public api
```cpp
- Renamed `ImGuiInputFlags_RouteGlobalLow` -> `ImGuiInputFlags_RouteGlobal` (this is the suggested global route)
- Renamed `ImGuiInputFlags_RouteGlobal` -> `ImGuiInputFlags_RouteGlobal | ImGuiInputFlags_RouteOverFocused`
- Renamed `ImGuiInputFlags_RouteGlobalHigh` -> `ImGuiInputFlags_RouteGlobal | ImGuiInputFlags_RouteOverFocused | ImGuiInputFlags_RouteOverActive`
```

I think it may boils down to changing:

```cpp
bool Shortcuts::checkShortcut(const ShortcutWithRepeat& shortcut) const
{
	assert(shortcut.keyChord != ImGuiKey_None);
	auto flags = (shortcut.type == one_of(GLOBAL, ALWAYS_GLOBAL) ? ImGuiInputFlags_RouteGlobalLow : 0)
	           | ImGuiInputFlags_RouteUnlessBgFocused
	           | (shortcut.repeat ? ImGuiInputFlags_Repeat : 0);
	return ImGui::Shortcut(shortcut.keyChord, 0, flags);
}
```
to
```cpp
bool Shortcuts::checkShortcut(const ShortcutWithRepeat& shortcut) const
{
	assert(shortcut.keyChord != ImGuiKey_None);
	auto flags = (shortcut.type == one_of(GLOBAL, ALWAYS_GLOBAL) ? ImGuiInputFlags_RouteGlobal : 0)
	           | ImGuiInputFlags_RouteUnlessBgFocused
	           | (shortcut.repeat ? ImGuiInputFlags_Repeat : 0);
	return ImGui::Shortcut(shortcut.keyChord, flags, 0);
}
```
Notice the parameter order change

**Comment by m9710797** [comment]
Thanks!!

We only recently upgraded to 1.90.6. Later (in a few weeks?) when we upgrade to 1.90.7 we'll make sure to apply your patch.

For stuff like this it would be nice to use stronger types. So that this would have resulted in a compilation error instead of wrong behavior. But I also understand we were using an unstable API, and that it comes with more risk. So again thanks a lot for notifying us!

**Comment by m9710797** [comment]
I upgraded to Dear ImGui "v1.90.8 WIP". Next to the above change, I also had to combine `ImGuiInputFlags_RouteGlobal` and `ImGuiInputFlags_RouteUnlessBgFocused`. Using the latter standalone triggers an assert now, which makes sense. After that it works fine. Thanks.
