### ISSUE TITLE
[Bug] wxCatapult doesn't compile with wx 2.9 [sf#445]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#839]
**Reported by manuelbi on 2012-12-03 09:52 UTC**
See https://sourceforge.net/projects/openmsx/forums/forum/119121/topic/6353627

Compiling CatapultPage... In file included from /usr/local/include/wx-2.9/wx/window.h:19:0, from /usr/local/include/wx-2.9/wx/control.h:23, from /usr/local/include/wx-2.9/wx/animate.h:20, from /usr/local/include/wx-2.9/wx/xrc/xmlres.h:29, from src/CatapultPage.cpp:6: /usr/local/include/wx-2.9/wx/event.h: In member function ‘bool CatapultPage::UpdateToggleSetting(wxString, wxString, wxString, int)’: /usr/local/include/wx-2.9/wx/event.h:3069:18: error: ‘virtual bool wxEvtHandler::ProcessEvent(wxEvent&)’ is inaccessible src/CatapultPage.cpp:185:30: error: within this context make: *** [derived/x86-linux-opt/obj/CatapultPage.o] Error 1

From the wxWidgets 2.9.x changes file: " wxWindow::ProcessEvent() (and other wxEvtHandler methods inherited by wxWindow) has been made protected to prevent wrongly using it instead of correct GetEventHandler()-&gt;ProcessEvent(). New ProcessWindowEvent() was added for convenience. " So it looks like the Catapult code is not compatible yet with wxWidgets 2.9.x.

**Comment by openMSX-import** [comment]
**Commented by joxy on 2013-07-24 04:50 UTC**
The "Current Stable Release" for wx is currently "wxWidgets 2.8.12", according to the wx site. IMHO it doesn't make sense to support 2.9.x for now, since 2.9.x are development releases.

**Comment by openMSX-import** [comment]
**Updated by joxy on 2013-07-30 03:17 UTC**
- **labels**: Catapult --> wxCatapult
- **summary**: Catapult doesn't compile with wx 2.9 --> wxCatapult doesn't compile with wx 2.9
- **status**: open --> closed-later

**Comment by openMSX-import** [comment]
**Commented by joxy on 2013-07-30 03:17 UTC**
1. I think I will not waste time on development releases of wx. Let it enter a 'stable' status, then I will fix.
1. Additionally, "ProcessEvent" code seems ridiculous for me. There should be a much simpler way to do things; I need to get rid of this event processing call completely, if possible.
