### ISSUE TITLE
A few build issues on Linux

### ISSUE THREAD

**Issue by cmitu** [openMSX/openMSX#1327]
I'm trying to build latest `master` on a few systems and, due to some recent changes, I get a build failure:

* Using Ubuntu 18.04 (x86_64), using `gcc` 7.5.0, the build fails with:
   ```
   In file included from src/settings/Setting.hh:8:0,
                 from src/settings/VideoSourceSetting.hh:4,
                 from src/MSXMotherBoard.hh:5,
                 from src/CartridgeSlotManager.cc:2:
    src/utils/StringOp.hh:7:10: fatal error: charconv: No such file or directory
    #include <charconv>
          ^-----------------
   ```
  It looks like the compiler is not fully C++17 compliant and it's missing `charconv` (https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html). It would probably fail on the next error also.

* On an Debian Stable (Buster), with `gcc` 8.30, the build fails with:
  ```
   src/fdc/DMKDiskImage.cc: In function ‘constexpr bool openmsx::isValidDmkHeader(const openmsx::DmkHeader&)’:
  src/fdc/DMKDiskImage.cc:39:23: error: call to non-‘constexpr’ function ‘bool ranges::all_of(InputRange&&, UnaryPredicate) [with InputRange = const unsigned char (&)[7]; UnaryPredicate = openmsx::isValidDmkHeader(const openmsx::DmkHeader&)::<lambda(auto:3&)>]’
  return ranges::all_of(header.reserved, [](auto& r) { return r == 0; }) &&
         -------------^-------------------------
   ```
  This seems to be caused by incomplete C++20 support in this version of `gcc` for `ranges::all_of` [introduced](https://en.cppreference.com/w/cpp/algorithm/ranges/all_any_none_of) in C++20.

Not sure if you want to keep compatibility with these older GCC version or just update the [compilation docs](http://openmsx.org/manual/compile.html) and change the `g++` required version from 7.

**Comment by m9710797** [comment]
Hi cmitu,

Thanks for reporting these issues!

OpenMSX should compile fine with a C++-17  compiler. That rules out gcc-7, but it should have worked with gcc-8. The failure you reported with gcc-8 was a mistake in our code, and I fixed it (in 6cbc40aa492). I also updated the compilation docs to require gcc-8 (instead of 7).

BTW: the ranges::all_of() function is our own re-implementation of std::ranges::all_of(). The idea is that in a few years we can switch to c++20 and drop our version of this function.

Wouter

**Comment by cmitu** [comment]
Thank you for the quick fix. 
[6cbc40a](https://github.com/openMSX/openMSX/commit/6cbc40aa4922ded08c2092961df964d77bf1229b) does solve the 2nd build problem on Debian (with gcc 8.3.0), though a similar error is thrown later on (looks like introduced in eda5ddeb).
```
src/utils/sha1.cc: In function ‘constexpr unsigned int openmsx::hex(char, const char*)’:
src/utils/sha1.cc:139:46: error: expression ‘<throw-expression>’ is not a constant expression
                     std::string_view(str, 40));
```
Let me know if you prefer to open a separate issue.

**Comment by m9710797** [comment]
I tested with gcc 8.4.0-4ubuntu, and that (already) compiled fine for me.
But I pushed a workaround. Let me know if this solves the issue for you.

**Comment by cmitu** [comment]
Yes, after aaa4fbc, compilation completes successfully with 8.3.0. Thank you.
